title: Sensorium Festival 2018
author:
  name: Unfold
  email: hello@unfold.is
ticket_url: https://ti.to/sensorium/sensorium-2018
metadata:
    description: Three days of workshops and talks bridging the fields of computational art, design and performance
    keywords: sensorium, conference, art, design, performance, technology, digital, bratislava, creative technology
    author: Unfold
    'og:title': Sensorium Festival 2018
    'og:description': Three days of workshops and talks bridging the fields of computational art, design and performance
    'og:type': website
    'og:url': http://sensorium.is/
    'og:site_name': Sensorium Festival 2018
    'og:image': http://sensorium.is/user/themes/imaginarious/images/social/sensorium-2018.jpg
    'og:locale': en_GB
    'og:locale:alternate': sk_SK
    'twitter:card' : summary_large_image
menu:
   - text: Tickets
     url: https://ti.to/sensorium/sensorium-2018
     classes: 'external link grow ba-l bw1 mt-1'
     newTab: true