title: Sensorium Conference 2017
author:
  name: Unfold
  email: hello@unfold.is
metadata:
    description: Two days of workshops and talks bridging the fields of computational art, design and performance
    keywords: sensorium, conference, art, design, performance, technology, digital, bratislava, creative technology
    author: Unfold
    'og:title': Sensorium Conference 2017
    'og:description': Three days of workshops and talks bridging the fields of computational art, design and performance
    'og:type': website
    'og:url': http://sensorium.is/
    'og:site_name': Sensorium Conference 2017
    'og:image': http://sensorium.is/user/themes/imaginarious/images/social/sensorium-cover.jpg
    'og:locale': en_GB
    'og:locale:alternate': sk_SK
    'twitter:card' : summary_large_image